### ISSUE TITLE
Check if alarm will wake the device

### ISSUE THREAD

**Issue by Red-Folder** [Red-Folder/Scheduler-Plugin#8]

**Comment by zeeshanjan82** [comment]
I am able to have the screen come up when the alarm fires if the phone is not locked but when the phone is locked I do not see the scheduler.html coming over the lock screen , it comes up but first I need to unlock the screen.

**Comment by Red-Folder** [comment]
@zeeshanjan82  See https://github.com/Red-Folder/Scheduler-Plugin/issues/15
